/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: './courses/fast.ai'}],

  // But you can create a sidebar manually
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Courses',
      link: {
        type: 'doc',
        id: 'courses/index-courses'
      },
      items: [
        {
          type: 'category',
          label: 'Coursera',
          link: {
            type: 'generated-index',
            title: 'Coursera Courses',
            description:
              "This section will cover the following courses:",
            keywords: ['coursera'],
            image: '/img/docusaurus.png',
          },
          items: [
            {
              type: 'category',
              label: 'Machine Learning',
              link: {
                type: 'doc',
                id: 'courses/coursera/machine-learning/README',
              },
              items: [
                {
                  type: 'category',
                  label: 'Week 1',
                  link: {
                    type: 'generated-index',
                    title: 'Week 1',
                    description:
                      "This section will cover the following topics:",
                    keywords: ['week-1'],
                    image: '/img/docusaurus.png',
                  },
                  items: [
                    'courses/coursera/machine-learning/week-1/introduction',
                  ],
                },
                {
                  type: 'category',
                  label: 'Week 2',
                  link: {
                    type: 'generated-index',
                    title: 'Week 2',
                    description:
                      "This section will cover the following topics:",
                    keywords: ['week-3'],
                    image: '/img/docusaurus.png',
                  },
                  items: [
                    'courses/coursera/machine-learning/week-2/linear-regression-with-multiple-variables',
                  ],
                },
              ],
            },
          ],
        },
        {
          type: 'autogenerated',
          dirName: 'courses/ai'
        },
      ]
    },
    {
      type: 'category',
      label: 'Books',
      link: {
        type: 'generated-index',
        title: 'Book Summaries',
        description:
          "Books I have read:",
        keywords: ['books'],
        image: '/img/docusaurus.png',
      },
      items: [
        'books/deep-work',
      ],
    },
    // {
    //   type: 'category',
    //   label: 'Books',
    //   link: {
    //     type: 'doc',
    //     id: 'books/index-books'
    //   },
    //   items: [
    //     'books/deep-work',
    //   ],
    // },
    {
      type: 'category',
      label: 'Resources',
      link: {
        type: 'generated-index',
        title: 'Resources',
        description:
          "A collection of links.",
        keywords: ['resources'],
        image: '/img/docusaurus.png',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'resources'
        },
      ],
    },
  ]
};

module.exports = sidebars;
